# Site settings
title: Ran Gu
contact_email_primary: "ran.gu@citystgeorges.ac.uk"
contact_email_secondary: "lionup@gmail.com"

# Keep this plain text for better SEO snippets
description: > 
  City St George’s, University of London. <br>
  Institute for Fiscal Studies.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rangu.org/"
github_username: lionup

# SEO
seo:
  description: "Ran Gu - Senior Lecturer (Associate Professor) at City St George’s, University of London; Research Associate at the Institute for Fiscal Studies."
  author: "Ran Gu"
  keywords: "Ran Gu, economics, household finance, macro labour, applied microeconomics, City St George’s, University of London"

# Social Links
social:
  linkedin: "https://www.linkedin.com/in/ran-gu-666192124/"
  twitter: "https://x.com/LionupRan"
  github: "https://github.com/lionup"
  bluesky: "https://bsky.app/profile/ran-gu.bsky.social"

# Homepage announcement
# announcement: "Our new research on flexible working & gender equality — with Baowen Xue, Heejung Chung & Anne McMunn — will soon appear in BMJ's Journal of Epidemiology & Community Health. Coverage via <a href='https://www.bloomberg.com/news/articles/2025-09-02/fathers-face-steeper-wage-cuts-when-stepping-back-from-work' target='_blank'>Bloomberg</a>."
# announcement: "New publication: <a href='https://doi.org/10.3982/QE1822' target='_blank'>Durables and Lemons: Private Information and the Market for Cars</a> (with Richard Blundell, Soren Leth-Petersen, Hamish Low & Costas Meghir) — Quantitative Economics, 2026. Also, <a href='https://jech.bmj.com/content/early/2025/09/13/jech-2025-224166' target='_blank'>Does the “right to request” flexible work policy influence men’s and women’s uptake of flexible working and well-being - Findings from the UK Household Longitudinal Study</a> (with Baowen Xue, Heejung Chung & Anne McMunn) - BMJ's Journal of Epidemiology & Community Health, 2025."
announcement: "New publication: <a href='https://doi.org/10.3982/QE1822' target='_blank'>Durables and Lemons: Private Information and the Market for Cars</a> (with Richard Blundell, Soren Leth-Petersen, Hamish Low & Costas Meghir) — Quantitative Economics, 2026."


# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-target-blank
  - jekyll-seo-tag
exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - node_modules

# Permalinks for specific sections
permalink: /:categories/:year/:month/:title/
cv_permalink: "/cv/:title/"
research_permalink: "/research/:title/"
teaching_permalink: "/teaching/:title/"
computing_permalink: "/computing/:title/"

# Job and other settings
job:
  title: "Senior Lecturer (Associate Professor)"
  institution: "City St George’s, University of London"
  research_focus: ["Household Finance", "Macro Labour", "Applied Microeconomics"]
excerpt_separator: "<!--more-->"

# Locale settings
lang: "en"
timezone: "Europe/London"
safe: true
